function introMobile() {
    var wWidth = $("#c1").innerWidth();
    var wHeight = $("#c1").innerHeight();
    var c = document.getElementById("c1");
    c.width = wWidth;
    c.height = wHeight;
    var ctx = c.getContext("2d");
    ctx.fillStyle="#009C00";
    ctx.moveTo(0,0);
    ctx.lineTo(wWidth,0);
    ctx.lineTo(wWidth,wHeight/4.3);
    ctx.lineTo(0,wHeight);
    ctx.lineTo(0,wHeight-wHeight/4.3);
    ctx.lineTo(wWidth,0);
    ctx.lineTo(wWidth,wHeight/4.3);
    ctx.lineTo(0,wHeight/4.3);
    ctx.lineTo(0,0);
    ctx.fill();
    ctx.fillStyle="white";
    ctx.font = "100 22px Open Sans";
    ctx.fillText("techie",30,28);
    c = document.getElementById("c2");
    c.width = wWidth;
    c.height = wHeight;
    ctx = c.getContext("2d");
    ctx.fillStyle="#008C00";
    ctx.moveTo(0,0);
    ctx.lineTo(wWidth,0);
    ctx.lineTo(wWidth,wHeight/4.3);
    ctx.lineTo(0,wHeight);
    ctx.lineTo(0,wHeight-wHeight/4.3);
    ctx.lineTo(wWidth,0);
    ctx.lineTo(wWidth,wHeight/4.3);
    ctx.lineTo(0,wHeight/4.3);
    ctx.lineTo(0,0);
    ctx.fill();
    ctx.fillStyle="white";
    ctx.font = "100 22px Open Sans";
    ctx.fillText("swift learner",30,28);
    c = document.getElementById("c3");
    c.width = wWidth;
    c.height = wHeight;
    ctx = c.getContext("2d");
    ctx.fillStyle="#007C00";
    ctx.moveTo(0,0);
    ctx.lineTo(wWidth,0);
    ctx.lineTo(wWidth,wHeight/4.3);
    ctx.lineTo(0,wHeight);
    ctx.lineTo(0,wHeight-wHeight/4.3);
    ctx.lineTo(wWidth,0);
    ctx.lineTo(wWidth,wHeight/4.3);
    ctx.lineTo(0,wHeight/4.3);
    ctx.lineTo(0,0);
    ctx.fill();
    ctx.fillStyle="white";
    ctx.font = "100 22px Open Sans";
    ctx.fillText("problem solver *",30,28);
    c = document.getElementById("c4");
    c.width = wWidth;
    c.height = wHeight;
    ctx = c.getContext("2d");
    ctx.fillStyle="#006D00";
    ctx.moveTo(0,0);
    ctx.lineTo(wWidth,0);
    ctx.lineTo(wWidth,wHeight/4.3);
    ctx.lineTo(0,wHeight);
    ctx.lineTo(0,wHeight-wHeight/4.3);
    ctx.lineTo(wWidth,0);
    ctx.lineTo(wWidth,wHeight/4.3);
    ctx.lineTo(0,wHeight/4.3);
    ctx.lineTo(0,0);
    ctx.fill();
    ctx.fillStyle="white";
    ctx.font = "100 22px Open Sans";
    ctx.fillText("challenge seeker",30,28);
}
function introDesktop() {
    var wWidth = $("#c1").innerWidth();
    var wHeight = $("#c1").innerHeight();
    var c = document.getElementById("c1");
    c.width = wWidth;
    c.height = wHeight;
    var ctx = c.getContext("2d");
    ctx.fillStyle="#009C00";
    ctx.moveTo(0,0);
    ctx.lineTo(wWidth,0);
    ctx.lineTo(wWidth,wHeight/4.3);
    ctx.lineTo(0,wHeight);
    ctx.lineTo(0,wHeight-wHeight/4.3);
    ctx.lineTo(wWidth,0);
    ctx.lineTo(wWidth,wHeight/4.3);
    ctx.lineTo(0,wHeight/4.3);
    ctx.lineTo(0,0);
    ctx.fill();
    ctx.fillStyle="white";
    ctx.font = "100 60px Open Sans";
    ctx.fillText("techie",80,65);
    c = document.getElementById("c2");
    c.width = wWidth;
    c.height = wHeight;
    ctx = c.getContext("2d");
    ctx.fillStyle="#008C00";
    ctx.moveTo(0,0);
    ctx.lineTo(wWidth,0);
    ctx.lineTo(wWidth,wHeight/4.3);
    ctx.lineTo(0,wHeight);
    ctx.lineTo(0,wHeight-wHeight/4.3);
    ctx.lineTo(wWidth,0);
    ctx.lineTo(wWidth,wHeight/4.3);
    ctx.lineTo(0,wHeight/4.3);
    ctx.lineTo(0,0);
    ctx.fill();
    ctx.fillStyle="white";
    ctx.font = "100 60px Open Sans";
    ctx.fillText("swift learner",80,65);
    c = document.getElementById("c3");
    c.width = wWidth;
    c.height = wHeight;
    ctx = c.getContext("2d");
    ctx.fillStyle="#007C00";
    ctx.moveTo(0,0);
    ctx.lineTo(wWidth,0);
    ctx.lineTo(wWidth,wHeight/4.3);
    ctx.lineTo(0,wHeight);
    ctx.lineTo(0,wHeight-wHeight/4.3);
    ctx.lineTo(wWidth,0);
    ctx.lineTo(wWidth,wHeight/4.3);
    ctx.lineTo(0,wHeight/4.3);
    ctx.lineTo(0,0);
    ctx.fill();
    ctx.fillStyle="white";
    ctx.font = "100 60px Open Sans";
    ctx.fillText("problem solver *",80,65);
    c = document.getElementById("c4");
    c.width = wWidth;
    c.height = wHeight;
    ctx = c.getContext("2d");
    ctx.fillStyle="#006D00";
    ctx.moveTo(0,0);
    ctx.lineTo(wWidth,0);
    ctx.lineTo(wWidth,wHeight/4.3);
    ctx.lineTo(0,wHeight);
    ctx.lineTo(0,wHeight-wHeight/4.3);
    ctx.lineTo(wWidth,0);
    ctx.lineTo(wWidth,wHeight/4.3);
    ctx.lineTo(0,wHeight/4.3);
    ctx.lineTo(0,0);
    ctx.fill();
    ctx.fillStyle="white";
    ctx.font = "100 60px Open Sans";
    ctx.fillText("challenge seeker",80,65);
}